Update ci-cd-pipeline.yml

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -138,17 +138,35 @@ jobs:
           kubectl create namespace argocd || echo "Namespace already exists"
           kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
 
+
+      - name: Change ArgoCD Service to LoadBalancer
+        run: |
+          kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
+          
+      - name: Wait for LoadBalancer External IP
+        run: |
+          echo "Waiting for ArgoCD External IP..."
+          for i in {1..30}; do
+            EXTERNAL_IP=$(kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+            if [[ -n "$EXTERNAL_IP" ]]; then
+              echo "ArgoCD External IP: $EXTERNAL_IP"
+              echo "ARGOCD_SERVER=https://$EXTERNAL_IP" >> $GITHUB_ENV
+              exit 0
+            fi
+            echo "Retrying in 10s..."
+            sleep 10
+          done
+          echo "Failed to get ArgoCD External IP"
+          exit 1
+
           
       - name: Retrieve ArgoCD Admin Password
         run: |
           kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
 
 
-      - name: Set up ArgoCD CLI
-        run: |
-          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
-          chmod +x argocd
-          sudo mv argocd /usr/local/bin/
+
+    
 
 
       - name: Authenticate with ArgoCD
